# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: Apalachee-Beekeepers-Association/website
  base_url: https://sveltia-cms-auth.violetro.se/

media_folder: /static/media
public_folder: /media
media_libraries:
  stock_assets:
    providers: []
      
collections:
  - name: events
    icon: calendar_month
    label: Events
    folder: /content/events
    media_folder: /static/media/events
    public_folder: /media/events
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Description
        widget: richtext
      - name: date
        label: Start
        widget: datetime
      - name: end
        label: End
        widget: datetime
        required: false
      - name: attachments
        label: Attachments
        multiple: true
        widget: file
  - name: posts
    label: Posts
    folder: /content/posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }